### ISSUE TITLE
博客页面排版错误

### ISSUE THREAD

**Issue by HowQi** [gtf35/live2d_unity_sdk_chinese_document#1]
不知道是不是应该在这里提issue, 介绍"更新导入的模型"这一节时,你的博客页面有一篇排版有大问题
https://blog.gtf35.top/cubism-sdk-tutorials-getting-started-reimportmodel/
全变成代码段了

**Comment by gtf35** [comment]
@HowQi 您好，感谢您的反馈，确实有问题，预计今晚修正。

另外一提，没想到真的能帮到别人，我也很开心

**Comment by gtf35** [comment]
已更正，感谢反馈

**Comment by HowQi** [comment]
感谢你的翻译,官网文档看起来真实头痛。(多亏了你的翻译 我甚至水了一篇[博客](https://www.cnblogs.com/qiiimiu/p/16964299.html)(x
